//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wholesale_base.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplies
    {
        public int id_Supplies { get; set; }
        public Nullable<int> id_provaider { get; set; }
        public Nullable<int> id_product { get; set; }
        public string delivery_price { get; set; }
        public string delivery_time { get; set; }
        public string quantity { get; set; }
        public string Account_number { get; set; }
        public string Photo { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual provider provider { get; set; }
    }
}
