//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wholesale_base.Classes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Wholesale_baseEntities : DbContext
    {
        public static Wholesale_baseEntities _context;
        public Wholesale_baseEntities()
            : base("name=Wholesale_baseEntities")
        {
        }
        public static Wholesale_baseEntities GetContext()
        {
            if (_context == null)
            {
                _context = new Wholesale_baseEntities();
            }
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<provider> provider { get; set; }
        public virtual DbSet<Supplies> Supplies { get; set; }
    }
}
